#    ______ _   _  _____
#   |  ____| \ | |/ ____|
#   | |__  |  \| | |
#   |  __| | . ` | |
#   | |____| |\  | |____
#   |______|_| \_|\_____|
#
#    CREATED BY ANHCRAFT

general:
  # the prefix of main chat messages
  prefix: "&f/&5ENC&f/ "

  # customize your locale for messages and texts
  # write the name of your wanted localization file here (checks it in the folder /locale/)
  # available: en-us.yml, vi-vn.yml
  locale_file: en-us.yml

  # should we use another thread for plugin-loading and plugin-reloading?
  # this option can improve the performance, but there will some unexpected errors
  # for example, if you reload the plugin, the locale file will be reloaded later, you may receive the message which using the old locale (though, we think it can be accepted)
  reload_async: true

# customize the saving of enchantment-configuration file
enchant_config_saver:
  # should we use another thread for saving?
  use_async: true
  # the delay duration for each file-saving time
  delay_duration: 100

# settings for commands
commands:
  # when interacts with enchantment, whether we use its id or its name?
  # warning: using names can make the performance worse
  use_enchantment_id: true

  # should we allow unsafe enchantment (enchanting unsupported items with unlimited level)?
  unsafe_enchantments: false

# =====================
# do not change this
config_version: ${enc.configVersion}